# Generated by Django 4.2.7 on 2023-12-05 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="films",
            old_name="ingredients",
            new_name="review",
        ),
        migrations.RemoveField(
            model_name="films",
            name="instructions",
        ),
    ]
